# Generated by Django 5.1.1 on 2024-10-07 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahaktables', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mtables',
        ),
    ]
