"""
Django settings for mojallal24mehr project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--o*rtwaxd%_%yz7t2505stw(r_l$ftjl^7l$c_nr5k4#hcjgj*'

# SECURITY WARNING: don't run with debug turned on in production!


# DEBUG = False
# sn = os.getenv('COMPUTERNAME')
# print('sn')
# print(sn)
# if sn in ('DESKTOP-ITU3EHV','TECH_MANAGER','DESKTOP-1ERPR1M'):
#     DEBUG = True
# else:
#     print('DEBUG=False')

DEBUG = True


ALLOWED_HOSTS = ['localhost','172.16.1.14','rp-mahak.ymv.ir']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_render_partial',
    'django_jalali',

    'mahaktables',
    'mahakupdate',
    'dashboard',
    'dashkala',
    'django_apscheduler',
    'custom_login',
    'accounting',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mojallal24mehr.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mojallal24mehr.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

#
# if sn in ('DESKTOP-ITU3EHV','TECH_MANAGER','DESKTOP-1ERPR1M'):
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.sqlite3',
#             'NAME': BASE_DIR / 'db.sqlite3',
#         }
#     }
# else:
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.mysql',
#             'NAME': 'yaskabod',  # نام دیتابیسی که می‌خواهید استفاده کنید
#             'USER': 'root',  # نام کاربری شما
#             'PASSWORD': 'YASRolikali514',  # پسوردی که برای کاربر root انتخاب کردید
#             'HOST': 'localhost',  # یا '127.0.0.1'
#             'PORT': '3306',  # پورت پیش‌فرض
#         }
#     }
#

DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# صرف نظر شد
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'yasdb',  # نام پایگاه داده
#         'USER': 'postgres',      # نام کاربری
#         'PASSWORD': 'rk32313231', # رمز عبور
#         'HOST': 'localhost',    # یا 127.0.0.1
#         'PORT': '5432',         # پورت پیش‌فرض PostgreSQL
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'fa-ir'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

# USE_L10N = True
USE_L10N = False

# USE_TZ = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/site_statics/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "assets")
]
STATIC_ROOT = os.path.join(BASE_DIR, "static_cdn", "static_root")

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "static_cdn", "media_root")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"  # Format for displaying run time timestamps in the Django admin site.
APSCHEDULER_RUN_NOW_TIMEOUT = 2500  # Seconds to wait for an explicitly requested job to complete.


AUTH_USER_MODEL = 'custom_login.CustomUser'
#