# Generated by Django 5.1.2 on 2024-11-26 20:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, default=0, null=True, verbose_name='شماره فاکتور')),
                ('pdate', models.CharField(blank=True, max_length=150, null=True, verbose_name='تاریخ شمسی')),
                ('mablagh_factor', models.FloatField(blank=True, default=0, null=True, verbose_name='مبلغ فاکتور')),
                ('takhfif', models.FloatField(blank=True, default=0, null=True, verbose_name='تخفیف')),
                ('create_time', models.CharField(blank=True, max_length=150, null=True, verbose_name='ساعت ایجاد')),
                ('darsad_takhfif', models.FloatField(blank=True, default=0, null=True, verbose_name='درصد تخفیف')),
                ('date', models.DateField(blank=True, null=True, verbose_name='تاریخ میلادی')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
            },
        ),
        migrations.CreateModel(
            name='KalaGroupinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0, verbose_name='کد اطلاعات گروه بندی')),
                ('cat1', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='دسته بندی 1')),
                ('cat2', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='دسته بندی 2')),
                ('cat3', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='دسته بندی 3')),
                ('contain', models.CharField(blank=True, max_length=300, verbose_name='شامل باشد')),
                ('not_contain', models.CharField(blank=True, max_length=300, verbose_name='شامل نباشد')),
            ],
            options={
                'verbose_name': 'شرط گروه بندی کالا',
                'verbose_name_plural': 'شروط گروه بندی کالا',
            },
        ),
        migrations.CreateModel(
            name='Mtables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_use', models.BooleanField(default=False, verbose_name='در حال استفاده است')),
                ('none_use', models.BooleanField(default=False, verbose_name=' بدون استفاده')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام جدول')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='توضیح')),
                ('row_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد ردیف ها')),
                ('cloumn_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد ستون ها')),
                ('last_update_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='آخرین آپدیت')),
                ('update_period', models.IntegerField(blank=True, default=60, null=True, verbose_name='بازه به\u200cروزرسانی (دقیقه)')),
                ('update_duration', models.FloatField(blank=True, null=True, verbose_name='مدت زمان به\u200cروزرسانی (ثانیه)')),
                ('update_priority', models.IntegerField(blank=True, default=0, null=True, verbose_name='اولویت آپدیت')),
            ],
            options={
                'verbose_name': 'جدول محک',
                'verbose_name_plural': 'جداول محک',
                'ordering': ['update_priority'],
            },
        ),
        migrations.CreateModel(
            name='PersonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0, verbose_name='کد گروه')),
                ('name', models.CharField(max_length=150, verbose_name='نام گروه')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'گروه ها',
            },
        ),
        migrations.CreateModel(
            name='Storagek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, default=0, null=True, verbose_name='کد انبار')),
                ('name', models.CharField(blank=True, default='-', max_length=150, null=True, verbose_name='نام انبار')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبار ها',
            },
        ),
        migrations.CreateModel(
            name='WordCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='کلمه')),
                ('count', models.IntegerField(verbose_name='تعداد')),
            ],
            options={
                'verbose_name': 'تکرار کلمه',
                'verbose_name_plural': 'کلمه',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام دسته\u200cبندی')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'سطح 1'), (2, 'سطح 2'), (3, 'سطح 3')], verbose_name='سطح')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='mahakupdate.category', verbose_name='دسته\u200cبندی والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Kala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0, verbose_name='کد کالا')),
                ('name', models.CharField(max_length=150, verbose_name='نام کالا')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kalas', to='mahakupdate.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
            },
        ),
        migrations.CreateModel(
            name='FactorDetaile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_factor', models.IntegerField(blank=True, default=0, null=True, verbose_name='شماره فاکتور')),
                ('radif', models.IntegerField(blank=True, default=0, null=True, verbose_name='ردیف')),
                ('code_kala', models.IntegerField(blank=True, default=0, null=True, verbose_name='کد کالا')),
                ('count', models.FloatField(blank=True, default=0, null=True, verbose_name='تعداد')),
                ('mablagh_vahed', models.FloatField(blank=True, default=0, null=True, verbose_name='مبلغ واحد')),
                ('mablagh_nahaee', models.FloatField(blank=True, default=0, null=True, verbose_name='مبلغ نهایی')),
                ('factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to='mahakupdate.factor')),
                ('kala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mahakupdate.kala')),
            ],
            options={
                'verbose_name': 'جزئیات فاکتور',
                'verbose_name_plural': 'جزئیات فاکتور ها',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0, verbose_name='کد فرد')),
                ('grpcode', models.IntegerField(default=0, verbose_name='کد گروه')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('lname', models.CharField(max_length=150, verbose_name='نام خانوادگی')),
                ('tel1', models.CharField(max_length=150, verbose_name='تلفن1')),
                ('tel2', models.CharField(max_length=150, verbose_name='تلفن2')),
                ('fax', models.CharField(max_length=150, verbose_name='فکس')),
                ('mobile', models.CharField(max_length=150, verbose_name='موبایل')),
                ('address', models.CharField(max_length=550, verbose_name='آدرس')),
                ('comment', models.CharField(max_length=550, verbose_name='توضیحات')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mahakupdate.persongroup')),
            ],
            options={
                'verbose_name': 'فرد',
                'verbose_name_plural': 'افراد',
            },
        ),
        migrations.CreateModel(
            name='Mojodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehousecode', models.IntegerField(blank=True, default=0, null=True, verbose_name='کد انبار')),
                ('code_kala', models.IntegerField(blank=True, default=0, null=True, verbose_name='کد کالا')),
                ('stock', models.FloatField(blank=True, default=0, null=True, verbose_name='موجودی')),
                ('total_stock', models.FloatField(blank=True, default=0, null=True, verbose_name='کل موجودی ')),
                ('averageprice', models.FloatField(blank=True, default=0, null=True, verbose_name='قیمت میانگین')),
                ('arzesh', models.FloatField(blank=True, default=0, null=True, verbose_name='ارزش')),
                ('kala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mahakupdate.kala')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mahakupdate.storagek')),
            ],
            options={
                'verbose_name': 'موجودی کالا',
                'verbose_name_plural': 'موجودی کالاها',
            },
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdate', models.CharField(blank=True, max_length=150, null=True, verbose_name='تاریخ شمسی')),
                ('date', models.DateField(blank=True, null=True, verbose_name='تاریخ میلادی')),
                ('percode', models.IntegerField(blank=True, default=0, null=True, verbose_name='کد شخص')),
                ('warehousecode', models.IntegerField(blank=True, default=0, null=True, verbose_name='کد انبار')),
                ('mablaghsanad', models.FloatField(blank=True, default=0, null=True, verbose_name='مبلغ سند')),
                ('code_kala', models.IntegerField(blank=True, default=0, null=True, verbose_name='کد کالا')),
                ('radif', models.IntegerField(blank=True, default=0, null=True, verbose_name='ردیف در فاکتور')),
                ('code_factor', models.IntegerField(blank=True, default=0, null=True, verbose_name='کد فاکتور')),
                ('count', models.FloatField(blank=True, default=0, null=True, verbose_name='تعداد')),
                ('averageprice', models.FloatField(blank=True, default=0, null=True, verbose_name='قیمت میانگین')),
                ('stock', models.FloatField(blank=True, default=0, null=True, verbose_name='موجودی')),
                ('is_prioritized', models.BooleanField(default=False)),
                ('factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mahakupdate.factor')),
                ('kala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mahakupdate.kala')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mahakupdate.storagek')),
            ],
            options={
                'verbose_name': 'کاردکس انبار',
                'verbose_name_plural': 'کاردکس های انبار',
                'ordering': ['-date', '-radif'],
            },
        ),
    ]
