# Generated by Django 5.1.1 on 2024-10-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0, verbose_name='کد کالا')),
                ('name', models.CharField(max_length=150, verbose_name='نام کالا')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
            },
        ),
        migrations.CreateModel(
            name='Mtables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_use', models.BooleanField(default=False, verbose_name='با استفاده / بدون استفاده')),
                ('name', models.CharField(max_length=150, verbose_name='نام جدول')),
                ('description', models.CharField(max_length=150, verbose_name='توضیح')),
            ],
            options={
                'verbose_name': 'جدول محک',
                'verbose_name_plural': 'جداول محک',
            },
        ),
    ]
