# Generated by Django 5.0.9 on 2024-10-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahakupdate', '0002_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='code',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='شماره فاکتور'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='create_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ساعت ایجاد'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='mablagh_factor',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='مبلغ فاکتور'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='pdate',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='تاریخ شمسی'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='takhfif',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='تخفیف'),
        ),
    ]
