# Generated by Django 5.0.9 on 2024-10-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahakupdate', '0003_alter_factor_code_alter_factor_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='create_time',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ساعت ایجاد'),
        ),
    ]
