# Generated by Django 5.0.3 on 2024-10-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahakupdate', '0004_alter_factor_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='darsad_takhfif',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='درصد تخفیف'),
        ),
    ]
