# Generated by Django 5.0.3 on 2024-10-08 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahakupdate', '0005_factor_darsad_takhfif'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorDetaile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_factor', models.IntegerField(blank=True, default=0, null=True, verbose_name='شماره فاکتور')),
                ('code_kala', models.IntegerField(blank=True, default=0, null=True, verbose_name='کد کالا')),
                ('count', models.FloatField(blank=True, default=0, null=True, verbose_name='تعداد')),
                ('mablagh_vahed', models.FloatField(blank=True, default=0, null=True, verbose_name='مبلغ واحد')),
                ('mablagh_nahaee', models.FloatField(blank=True, default=0, null=True, verbose_name='مبلغ نهایی')),
                ('factor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='mahakupdate.factor')),
                ('kala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mahakupdate.kala')),
            ],
            options={
                'verbose_name': 'جزئیات فاکتور',
                'verbose_name_plural': 'جزئیات فاکتور ها',
            },
        ),
    ]
