# Generated by Django 5.1.2 on 2024-10-14 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahakupdate', '0006_factordetaile'),
    ]

    operations = [
        migrations.AddField(
            model_name='factordetaile',
            name='radif',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ردیف'),
        ),
        migrations.AddField(
            model_name='mtables',
            name='cloumn_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد ستون ها'),
        ),
        migrations.AddField(
            model_name='mtables',
            name='none_use',
            field=models.BooleanField(default=False, verbose_name=' بدون استفاده'),
        ),
        migrations.AddField(
            model_name='mtables',
            name='row_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد ردیف ها'),
        ),
        migrations.AlterField(
            model_name='factordetaile',
            name='factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='mahakupdate.factor'),
        ),
        migrations.AlterField(
            model_name='mtables',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='توضیح'),
        ),
        migrations.AlterField(
            model_name='mtables',
            name='in_use',
            field=models.BooleanField(default=False, verbose_name='در حال استفاده است'),
        ),
        migrations.AlterField(
            model_name='mtables',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نام جدول'),
        ),
    ]
