# Generated by Django 5.0.9 on 2024-10-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahakupdate', '0006_factordetaile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtables',
            name='cloumn_count',
            field=models.IntegerField(default=0, verbose_name='تعداد ردیف ها'),
        ),
        migrations.AddField(
            model_name='mtables',
            name='row_count',
            field=models.IntegerField(default=0, verbose_name='تعداد ردیف ها'),
        ),
    ]
