# Generated by Django 5.0.9 on 2024-10-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahakupdate', '0007_mtables_cloumn_count_mtables_row_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtables',
            name='none_use',
            field=models.BooleanField(default=False, verbose_name=' بدون استفاده'),
        ),
        migrations.AlterField(
            model_name='mtables',
            name='cloumn_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد ستون ها'),
        ),
        migrations.AlterField(
            model_name='mtables',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='توضیح'),
        ),
        migrations.AlterField(
            model_name='mtables',
            name='in_use',
            field=models.BooleanField(default=False, verbose_name='در حال استفاده است'),
        ),
        migrations.AlterField(
            model_name='mtables',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نام جدول'),
        ),
        migrations.AlterField(
            model_name='mtables',
            name='row_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد ردیف ها'),
        ),
    ]
