# Generated by Django 5.0.9 on 2024-10-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahakupdate', '0008_mtables_none_use_alter_mtables_cloumn_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='radif',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ردیف'),
        ),
    ]
