# Generated by Django 5.0.9 on 2024-10-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahakupdate', '0009_factor_radif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='radif',
        ),
        migrations.AddField(
            model_name='factordetaile',
            name='radif',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ردیف'),
        ),
    ]
