# Generated by Django 5.0.9 on 2024-10-13 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahakupdate', '0010_remove_factor_radif_factordetaile_radif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factordetaile',
            name='factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='mahakupdate.factor'),
        ),
    ]
