# Generated by Django 5.1.2 on 2024-10-15 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahakupdate', '0007_factordetaile_radif_mtables_cloumn_count_and_more'),
        ('mahakupdate', '0011_alter_factordetaile_factor'),
    ]

    operations = [
    ]
