# Generated by Django 5.1.2 on 2024-10-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahakupdate', '0014_category_kala_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ میلادی'),
        ),
    ]
