# Generated by Django 5.1.2 on 2024-10-17 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahakupdate', '0015_factor_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='mahakupdate.category', verbose_name='دسته\u200cبندی والد'),
        ),
        migrations.AlterField(
            model_name='factordetaile',
            name='factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to='mahakupdate.factor'),
        ),
        migrations.AlterField(
            model_name='factordetaile',
            name='kala',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mahakupdate.kala'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kalas', to='mahakupdate.category', verbose_name='دسته\u200cبندی'),
        ),
    ]
