# Generated by Django 5.1.2 on 2024-10-18 06:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahakupdate', '0016_alter_category_parent_alter_factordetaile_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtables',
            name='last_update_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='آخرین آپدیت'),
        ),
        migrations.AddField(
            model_name='mtables',
            name='update_period',
            field=models.IntegerField(blank=True, default=60, null=True, verbose_name='بازه به\u200cروزرسانی (دقیقه)'),
        ),
    ]
