# Generated by Django 5.1.2 on 2024-10-18 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahakupdate', '0018_mtables_update_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdate', models.CharField(blank=True, max_length=150, null=True, verbose_name='تاریخ شمسی')),
                ('date', models.DateField(blank=True, null=True, verbose_name='تاریخ میلادی')),
                ('percode', models.IntegerField(blank=True, default=0, null=True, verbose_name='کد شخص')),
                ('warehousecode', models.IntegerField(blank=True, default=0, null=True, verbose_name='کد انبار')),
                ('mablaghsanad', models.FloatField(blank=True, default=0, null=True, verbose_name='مبلغ سند')),
                ('code_kala', models.IntegerField(blank=True, default=0, null=True, verbose_name='کد کالا')),
                ('code_factor', models.IntegerField(blank=True, default=0, null=True, verbose_name='کد فاکتور')),
                ('count', models.FloatField(blank=True, default=0, null=True, verbose_name='تعداد')),
                ('averageprice', models.FloatField(blank=True, default=0, null=True, verbose_name='قیمت میانگین')),
                ('stock', models.FloatField(blank=True, default=0, null=True, verbose_name='موجودی')),
                ('factor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mahakupdate.factor')),
                ('kala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mahakupdate.kala')),
            ],
            options={
                'verbose_name': 'کاردکس انبار',
                'verbose_name_plural': 'کاردکس های انبار',
            },
        ),
    ]
