# Generated by Django 5.1.2 on 2024-10-18 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahakupdate', '0019_kardex'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardex',
            name='radif',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ردیف در فاکتور'),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mahakupdate.factor'),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='kala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mahakupdate.kala'),
        ),
    ]
