# Generated by Django 5.1.2 on 2024-10-18 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahakupdate', '0020_kardex_radif_alter_kardex_factor_alter_kardex_kala'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0, verbose_name='کد گروه')),
                ('name', models.CharField(max_length=150, verbose_name='نام گروه')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'گروه ها',
            },
        ),
        migrations.AlterModelOptions(
            name='kardex',
            options={'ordering': ['pdate', 'radif'], 'verbose_name': 'کاردکس انبار', 'verbose_name_plural': 'کاردکس های انبار'},
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0, verbose_name='کد فرد')),
                ('grpcode', models.IntegerField(default=0, verbose_name='کد گروه')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('lname', models.CharField(max_length=150, verbose_name='نام خانوادگی')),
                ('tel1', models.CharField(max_length=150, verbose_name='تلفن1')),
                ('tel2', models.CharField(max_length=150, verbose_name='تلفن2')),
                ('fax', models.CharField(max_length=150, verbose_name='فکس')),
                ('mobile', models.CharField(max_length=150, verbose_name='موبایل')),
                ('address', models.CharField(max_length=550, verbose_name='آدرس')),
                ('comment', models.CharField(max_length=550, verbose_name='توضیحات')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mahakupdate.persongroup')),
            ],
            options={
                'verbose_name': 'فرد',
                'verbose_name_plural': 'افراد',
            },
        ),
    ]
