# Generated by Django 5.1.2 on 2024-10-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahakupdate', '0021_persongroup_alter_kardex_options_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kardex',
            options={'ordering': ['-pdate', '-radif'], 'verbose_name': 'کاردکس انبار', 'verbose_name_plural': 'کاردکس های انبار'},
        ),
    ]
