# Generated by Django 5.1.2 on 2024-10-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahakupdate', '0022_alter_kardex_options_alter_kardex_pdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardex',
            name='pdate',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='تاریخ شمسی'),
        ),
    ]
