# Generated by Django 5.1.2 on 2024-10-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahakupdate', '0022_alter_kardex_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardex',
            name='is_prioritized',
            field=models.BooleanField(default=False),
        ),
    ]
