# Generated by Django 5.1.2 on 2024-10-25 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahakupdate', '0023_alter_kardex_pdate'),
        ('mahakupdate', '0023_kardex_is_prioritized'),
    ]

    operations = [
    ]
