# Generated by Django 5.1.2 on 2024-11-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahakupdate', '0025_alter_mtables_options_mtables_update_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='KalaGroupinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0, verbose_name='کد اطلاعات گروه بندی')),
                ('cat1', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='دسته بندی 1')),
                ('cat2', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='دسته بندی 2')),
                ('cat3', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='دسته بندی 3')),
                ('contain', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='شامل باشد')),
                ('not_contain', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='شامل نباشد')),
            ],
            options={
                'verbose_name': 'شرط گروه بندی کالا',
                'verbose_name_plural': 'شروط گروه بندی کالا',
            },
        ),
    ]
