# Generated by Django 5.1.2 on 2024-11-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahakupdate', '0028_alter_kalagroupinfo_contain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storagek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, default=0, null=True, verbose_name='کد انبار')),
                ('name', models.CharField(blank=True, default='-', max_length=150, null=True, verbose_name='نام انبار')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبار ها',
            },
        ),
    ]
