# Generated by Django 5.1.2 on 2024-11-12 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahakupdate', '0029_storagek'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardex',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mahakupdate.storagek'),
        ),
    ]
