# Generated by Django 5.1.2 on 2024-11-18 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahakupdate', '0030_kardex_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mojodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdate', models.CharField(blank=True, max_length=150, null=True, verbose_name='تاریخ شمسی')),
                ('date', models.DateField(blank=True, null=True, verbose_name='تاریخ میلادی')),
                ('warehousecode', models.IntegerField(blank=True, default=0, null=True, verbose_name='کد انبار')),
                ('code_kala', models.IntegerField(blank=True, default=0, null=True, verbose_name='کد کالا')),
                ('averageprice', models.FloatField(blank=True, default=0, null=True, verbose_name='قیمت میانگین')),
                ('stock', models.FloatField(blank=True, default=0, null=True, verbose_name='موجودی')),
                ('kala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mahakupdate.kala')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mahakupdate.storagek')),
            ],
            options={
                'verbose_name': 'موجدی کالا',
                'verbose_name_plural': 'موجودی کالاها',
            },
        ),
    ]
