# Generated by Django 5.1.2 on 2024-11-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahakupdate', '0031_mojodi'),
    ]

    operations = [
        migrations.AddField(
            model_name='mojodi',
            name='arzesh',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='ارزش'),
        ),
    ]
